const greetings = [
  'Welcome! Dive into the heart of creativity.',
  '¡Bienvenido! Explora lo mejor de nuestras ideas.',
  "Here's to curiosity—let's explore together!",
  'Inspirasi ada di sini—nikmati setiap momen di situs kami.',
  'Find inspiration around every corner.',
  "Bienvenue! Découvrez un monde d'idées infinies.",
  'Unlock endless possibilities with us.',
  'เปิดโลกแห่งความคิดสร้างสรรค์กับเรา!',
  'Selamat datang! Keajaiban dimulai di sini.',
  'Discover something extraordinary, just for you!',
  'ここにあるすべてが、あなたの発見を待っています。',
  'Explore, imagine, and create—your journey starts now.',
  '歡迎來到我們的世界，開始屬於你的旅程！',
  'From dreams to reality—step into our world.',
  'برحلة مذهلة في انتظارك هنا، أهلا بك.',
  'Our site is your playground—have fun!',
  'Keberanianmu membawa keajaiban. Mulai di sini.',
  'Every click brings you closer to something special.',
  'Мы рады видеть вас здесь. Откройте для себя новое!',
  'Navigate through wonders and let curiosity lead the way.',
  'Bạn đã sẵn sàng khám phá điều tuyệt vời? Bắt đầu ngay!',
  "Let's make today a day of discovery!",
  'Your next adventure begins here.',
  'Langkah kecilmu membawa dampak besar. Mulai sekarang!',
  'Explore beyond the ordinary—start your journey now.',
]

export default greetings
