name: Setup and cache
description: Setup for node, pnpm and nx
inputs:
  node-version:
    required: false
    description: Node version for setup-node
    default: 18.x
runs:
  using: composite
  steps:
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v2

    - name: Install pnpm
      uses: pnpm/action-setup@v2.2.1
      with:
        version: '7.x'

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'pnpm'
