name: Setup and cache
description: Setup for node, pnpm and nx
inputs:
  node-version:
    required: false
    description: Node version for setup-node
    default: 18.x
runs:
  using: composite
  steps:
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v3.0.0
      with:
        version: '8.6.x'

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21.x'
        cache: 'pnpm'
