ignore:
  - 'apps/*'
  - 'packages/*'
comment:
  layout: " diff, flags, files, components"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false