name: wc-push-coverage
on:
  workflow_call:
    inputs:
      workflow_run_id: 
        required: true
        type: string
      workflow:
        required: true
        type: string
jobs:
  push-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download coverage reports artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: ${{ vars.COVERAGE_NAME }}
          path: ${{ vars.COVERAGE_PATH }}
          workflow: ${{ inputs.workflow }}
          run_id: ${{ inputs.workflow_run_id }}
          search_artifacts: true

      - name: Push coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        env:
          slug: itsferdiardiansa/ferdiardiansa.com
        with:
          files: ${{ vars.COVERAGE_FILE_JSON }}
          token: ${{ secrets.CODECOV_TOKEN }}